#!/bin/bash -x
yum -y install python3-pip
yum -y install python3-devel gsl-devel gcc
# min-pip test is to install as little as possible via pip
yum -y install \
  python3-numcodecs \
  python3-pyrsistent \
  python3-asciitree \
  python3-zarr \
  python3-lmdb \
  python3-h5py \
  python3-attrs \
  python3-jsonschema \
  python3-svgwrite \
  python3-six \
  python3-zipp \
  python3-importlib-metadata

